---
documentclass: article
fontsize: 12pt
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2: 
    toc: false
    latex_engine: xelatex
    fig_caption: yes
    includes:
      in_header: preamble.sty
      before_body: titlepage.sty
bibliography: references.bib  
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(haven) # to read SAS files
library(kableExtra)
library(qwraps2)
library(rprojroot)
library(patchwork)
library(psych)
library(gtools)

knitr::opts_chunk$set(echo = TRUE)
```

```{r load, include=FALSE, message=FALSE, warning=FALSE}
trichotomization <- c(-1000, 6, 25, 120)
data <- read_sas("data/hearing500lr.sas7bdat") %>%
  mutate(side = as.factor(side),
         id = as.factor(id),
         age_measurement = age + TIME,
         age_discrete = cut(age,
                            breaks = c(0,30,50,70,100),
                            labels = c("<30", "30-50", "50-70",">70")),
         y_discrete = cut(y,
                            breaks = trichotomization,
                            labels = c("Normal", "Reduced", "Bad")),
         learning = 1*(TIME == 0))
```
# Data trichotomization

# Marginal model
Q2

# Random-effects model
Q2

```{r}
library(multgee)
```

```{r}
# fit <- ordLORgee(formula = y_discrete ~ age+I(age^2)+TIME+learning,
#                  link = "logit", id = id, data = data,
#                  LORstr = "time.exch")#category.exch"
# summary(fit)
# 
# 
# # fit1 <- update(fit, formula = ~. +I(age^3)+ I(TIME^2))
# # waldts(fit, fit1)
```

```{r}
load("fit.Rdata")
```

```{r}
sum=summary(fit)
sum


plot(x=fit[["fitted.values"]][,1],y=fit[["fitted.values"]][,1])
plot(x=(data$age+data$TIME),y=fit[["fitted.values"]][,1])
plot(x=(data$age+data$TIME),y=fit[["fitted.values"]][,2])
plot(x=(data$age+data$TIME),y=fit[["fitted.values"]][,3])

plot(x=(data$age+data$TIME),y=fit[["fitted.values"]][,1],col="blue",ylim = range(0,1))
points(x=(data$age+data$TIME),y=fit[["fitted.values"]][,2],col="red")
points(x=(data$age+data$TIME),y=fit[["fitted.values"]][,3],col="green")
```

## Empirical Bayes prediction
Q3


```{r}
samples=100000

ageden=density(rnorm(samples,mean=fit$coefficients[[3]],sd=sum$coefficients[3,2]))
age2den=density(rnorm(samples,mean=fit$coefficients[[4]],sd=sum$coefficients[4,2]))
timeden=density(rnorm(samples,mean=fit$coefficients[[5]],sd=sum$coefficients[5,2]))
learnden=density(rnorm(samples,mean=fit$coefficients[[5]],sd=sum$coefficients[6,2]))

plot(ageden)
plot(age2den)
plot(timeden)
plot(learnden)
```

```{r}
library(ordinal)
load("remod.Rdata")
sumre=summary(remod)
sumre
```

```{r}
set.seed(100)

nids=10
simre=rep(rnorm(nids,mean=0,sd=sumre$ST[[1]][1]),samples/nids)
simage=rep(runif(nids,-2.5,2.5),samples/nids)
simage2=simage^2
simTIME=runif(samples,0,20)
simlearn=sample(c(0,1),samples,replace=T)
simagetime=simage*simTIME

simmat=matrix(c(simre,simage,simage2,simTIME,simlearn,simagetime,rep(0,samples)),ncol=7)

coefs=matrix(c(1,sumre$coefficients[3:7,1],0),ncol=1)

simpreds=simmat%*%coefs

library(locfit)

simmat[,7]=expit(simpreds)

simdf=as.data.frame(simmat)
colnames(simdf)=c("re","age","age2","TIME","learn","age:time","preds")



simdf_sort=simdf%>%arrange(re,age)

simdf_sort$age_rescale=simdf_sort$age*attr(sumre$model[,2],"scaled:scale")+attr(sumre$model[,2],"scaled:center")
simdf_sort$age2_rescale=simdf_sort$age^2

fakeids=sort(rep(1:nids,samples/nids))

simdf_sort=simdf_sort%>%
  mutate(ids=as.factor(fakeids),
         age_discrete = case_when(age_rescale<30~"0-30",
                                  age_rescale<50~"30-50",
                                  age_rescale<70~"50-70",
                                  age_rescale>70~"70+")
         )

thresholds=c(expit(sumre$coefficients[1]),expit(sumre$coefficients[2]))

simdf_sort%>%
  ggplot(aes(x=TIME,y=preds))+
  geom_smooth(aes(group=ids,color=age_discrete),se=F)+
  geom_smooth(aes(color="avg"),size=3)+
  geom_hline(aes(yintercept =  thresholds[2],linetype="Normal"),color="blue")+
  geom_hline(aes(yintercept =  thresholds[1],linetype="Excelent"),color="red")
  

```


# Transition model
Q4

# Discussion


# Bibliography
