---
title: "Untitled"
author: "Kendall Brown r0773111"
date: "11/7/2022"
output: pdf_document
---

```{r}
library(sas7bdat)
library(tidyverse)
library(car)
library(tseries)
library(lme4)
library(nlme)
library(gee)
```

```{r}
data=read.sas7bdat("hearing500lr.sas7bdat")
#data$id=as.factor(data$id)
data$yscale=2^(data$y/3)
data$id=as.factor(data$id)
data$isold=data$age>=55
data$learning=data$TIME==0
```

```{r}
data.right=data[data$side=="right",]
data.left=data[data$side=="left",]
```

GAUS
```{r}
model1=nlme::lme(y~age*TIME+I(TIME^2)+isold:I(age^3),data=data,random=~1|id/side,cor=corGaus())
AIC(model1)
```

LIN
```{r}
model2=nlme::lme(y~age*TIME+I(TIME^2)+isold:I(age^3),data=data,random=~1|id/side,cor=corLin())
AIC(model2)
```

Exp
```{r}
model3=nlme::lme(y~age*TIME+I(TIME^2)+isold:I(age^3),data=data,random=~1|id/side,cor=corExp())
AIC(model3)
```

CAR1
```{r}
model4=nlme::lme(y~age*TIME+I(age^2)+I(TIME^2)+isold:I(TIME^2),data=data,random=~1|id/learning/side,cor=corCompSymm())
AIC(model4)
mean(sqrt(model4$residuals^2))
```

```{r}
model4$coefficients
```
```{r}
model5=nlme::lme(y~age*TIME+I(TIME^2)+isold:I(TIME^3),data=data,random=~1|id/learning/side,cor=corCAR1())

anova(model4,model5)
```
